### ISSUE TITLE
Clarify Repo

### ISSUE THREAD

**Issue by asmod3us** [jailmanager/jailman#116]
This repo: https://github.com/jailmanager/jailman

mentions to `git clone https://github.com/Ornias1993/jailman.git`. Is that correct, or should we `git clone` this repo instead?

**Comment by Ornias1993** [comment]
@asmod3us The repo has just been moved, I'll try and do my best to update everything, but I cant work magic. 

If you find any small references that are still wrong, feel free to report them to: #56
:)
