### ISSUE TITLE
Cancelled jail creation might require manual intervention

### ISSUE THREAD

**Issue by Ornias1993** [jailmanager/jailman#13]
Manual intervention might be required if someone cancels jail creation, FreeNAS would request manual destroy a snapshot of the previous creation attempt.

It would be nice to detect this ourselves or at least try removing the snapshot on failure and retrying creation another time.

**Comment by Ornias1993** [comment]
Example of the error in question:
```
Snapshot: tank/iocage/releases/11.3-RELEASE/root@lidarr exists!
Please manually run zfs destroy tank/iocage/releases/11.3-RELEASE/root@lidarr if you wish to destroy it.
Failed to create jail
```

**Comment by Ornias1993** [comment]
Basically we need to catch this error and just run the snapshot destroy command.
(we don't care about snapshotting throw-away jails anyway)

**Comment by asmod3us** [comment]
i think i ran into that recently and passing `-fR` to iocage destroy would get this sorted?

**Comment by asmod3us** [comment]
So the scenario would be an install fails and this message is encountered when attempting a reinstall with `-r`? I will add `-fR` to both our `iocage destroy` calls

**Comment by Ornias1993** [comment]
@asmod3us Not -r only, also just -i with when iocage create failed beforehand.
You sure you want this:
`[-r | --release]	  Destroy a specified RELEASE dataset.`

**Comment by asmod3us** [comment]
any steps to reproduce such an issue? looks like we we would have to parse iocage output and clean up that release dataset?

**Comment by Ornias1993** [comment]
Afaik:
1. Start iocage create
2. hold ctrl+c

**Comment by asmod3us** [comment]
I'm getting this when I do that:
```
❯ iocage list
JAIL is missing it's configuration, please destroy this jail and recreate it.
+-----+--------------+---------+--------------+------+
| -   | sabnzbd3     | CORRUPT | N/A          | N/A  |
+-----+--------------+---------+--------------+------+
```

And a regular `iocage destroy JAIL` got rid of it again, so the above error looks like a different situation.

**Comment by Ornias1993** [comment]
Well at least it now just stops running after this error, thats something :)

**Comment by asmod3us** [comment]
Yes, that is true. And the error message tells you the jail already exists. Then the user can intervene...

**Comment by Ornias1993** [comment]
> Yes, that is true. And the error message tells you the jail already exists. Then the user can intervene...

Well, it isn't the jail that's existing it's a snapshot...
But yes, it literally tells you what you should copy-paste....

So with the error catching in, I doubt this is a real "bug" anymore, because there is an error during install and the user has to solve it and gets instructions how to solve it....

**Comment by asmod3us** [comment]
I just ran into that again, and if it occurs, there isn't even a jail present yet. Running the indicated zfs destroy seem to fix it then. I don't think we want to do that for the user.

**Comment by Ornias1993** [comment]
Got it.
