### ISSUE TITLE
Add further hardware transcoding support

### ISSUE THREAD

**Issue by Ornias1993** [jailmanager/jailman#139]
# Issue Template
### Detailed Bug Report
It would be nice putting some work into adding more hardware transcoding support.

A good start would be porting the work by @thorsteneb on: 
https://github.com/danb35/freenas-iocage-plex/commit/83eaea513c44a8ca2317da6c6907269400485f7e

**Comment by Ornias1993** [comment]
@thorsteneb Would you mind looking into integrating those changes?
It should be relatively doable now that we simplified how variables are setup in the dev branch....

**Comment by thorsteneb** [comment]
Won't happen anytime soon, I'm behind on other stuff. I'd say have someone else lead that effort.

**Comment by Ornias1993** [comment]
I don't "have" people do things.
People volunteer or I ask politely if I know they already did something.

**Comment by Ornias1993** [comment]
Closed due to being merged into dev branch
