### ISSUE TITLE
Unifi database not created in InfluxDB

### ISSUE THREAD

**Issue by colemamd** [jailmanager/jailman#151]
# Issue Template

## Description
When creating the Unifi jail w/ integrated Controller, the unifi database is not being created in Influx.

### Steps to Reproduce

1. Create Influx jail and Unifi Jail 
2.  Observe no unifi database being created
3.  

Noticed this when testing Grafana. I'll take a look when I get to the Unifi fixes.

**Comment by Ornias1993** [comment]
Hmm odd..
I think this will be the last issue for 1.2.3...
