### ISSUE TITLE
Add TrueNAS 12 support

### ISSUE THREAD

**Issue by Ornias1993** [jailmanager/jailman#170]
# Issue Template
### Detailed Bug Report
According to the release schedule for TrueNAS 12, we should get ready for TrueNAS 12 support.
SeeL https://www.ixsystems.com/community/threads/truenas-12-0-schedule.85194/

We will NOT support TrueNAS 12 with version 1.2.3, but 1.3.0 should support TrueNAS 12.
I'll edit the roadmap on jailmanager.org accordingly.

**Comment by thorsteneb** [comment]
One way to do this would be to remove the "version:" global, and leave it up to iocage which release to base the jail on. iocage will default to the OS version.

I don't know where else jailmain relies on FreeNAS / TrueNAS version. The Plex blueprint hw_transcoding.sh is expected to work as-is, as the middleware API didn't change afaik. Worth testing.

**Comment by Ornias1993** [comment]
@thorsteneb I recieve a lot of comments from you, without toroughly understanding the issue.
This is the last one, if you don't know what is meant with an issue, please ask questions instead of filling in the blanks yourself.

If it isn't an issue you are working on or have reported, please refraign from commenting.

In this case it was just about TESTING, it had nothing to do with relying on anything and it also has nothing to do with the version tag.

I appreciate you are trying to be helpfull, but you aren't helping.

**Comment by thorsteneb** [comment]
> and it also has nothing to do with the version tag

The version tag determines the release iocage installs. Currently, then, 11.3-RELEASE, which arguably should be 11.3-RELEASE for FreeNAS 11.3 and 12.1-RELEASE for TrueNAS 12.0.

Ways I can see to handle that:
- Set version: according to FreeNAS / TrueNAS version, which requires updating jailman whenever TrueNAS is updated, to keep in sync.
- Or remove version: altogether, iocage will then default to the OS release: 11.3-RELEASE for FreeNAS 11.3, 12.1-RELEASE for TrueNAS 12.0

Without addressing this, testing jailman on 12.0 is tricky: It'll continue to install 11.3-RELEASE jails, which is not recommended by ix if I read release notes correctly.

As you do not want suggestions related to testing, or on issues I did not create, I will step back from testing on 12.0.

> without toroughly understanding the issue

If I've missed something, point me to it, please. This is obviously not my code, I'm reading between the lines.

> If it isn't an issue you are working on or have reported, please refraign from commenting

Clear enough, I shall do that from here on out.

> I appreciate you are trying to be helpful

Indeed. Not to the point of causing aggravation to you and me, however. I'll step back.

**Comment by Ornias1993** [comment]
"Without addressing this, testing jailman on 12.0 is tricky: It'll continue to install 11.3-RELEASE jails, which is not recommended by ix if I read release notes correctly."

Why is this tricky? Just change the version accordingly, like how it is designed to be done?

**Comment by thorsteneb** [comment]
> Why is this tricky?

I should clarify: Testing jailman on 12.0 from an end user perspective is tricky. My assumption is that jailman will, eventually, support FreeNAS and TrueNAS Core seamlessly, choosing the "right" release for jails depending on where it finds itself. That is the functionality I was commenting on. If that is not the plan, the comment is indeed moot.

The user experience of changing version: in ```global.yml`` will be that this change is reverted through the gitupdate() function, in the version of jailman I tested.

**Comment by Ornias1993** [comment]
Every version of jailman would (just) support one verion of FreeNAS/TrueNAS. There currently are barely enough people to provide support and fixes to keep one version up....
That being said: A flag to disable auto-update is something I would consider.

**Comment by Ornias1993** [comment]
A few notes and decisions I made in regards to this discussion:
- The jail version to install will indeed be auto decided in the future. Just because it might still work with 11.3, doesn't mean we officially support it, so we can just as well implement it.

> The user experience of changing version: in global.yml will be that this change is reverted through the gitupdate() function
- Users shouldn't (have to) touch global.yml, but if they create a fork before doing so, the new version(s) auot-updater should follow their fork automatically and not the main repo
- I'll add "auto-update override" issue and plan it for 1.3.0, it's a small fix, that might be relevant for a lot of people that want to play with things instead of running what we serve.

Thanks for your feedback.

**Comment by Ornias1993** [comment]
The dev branch now autograbs the right version (12.1 for TrueNAS CORE atm) and at least the basic functionality of JailMan works.
