### ISSUE TITLE
[Discussion] Bashing-Bash

### ISSUE THREAD

**Issue by Ornias1993** [jailmanager/jailman#171]
As brought up by @asmod3us it might be interesting to move some (or even eventually all) code to Python instead of bash.

This Issue is create to give an easy point of entry for discussing this.

Some pro's:
- Easier implementation of more advanced data-processing features (like parsing config files)
- Cleaner code (subjective)
- More tools at our disposal
- The option of creating Unittests

Some Cons:
- Might not be supported for every by stock FreeNAS
- Might be less accessable for blueprint creators (not an issue if we only move the core code to python)

**Comment by asmod3us** [comment]
Are there plans in FreeNAS/TrueNAS to move away from Python?

**Comment by Ornias1993** [comment]
Ill ask Kris (Moore)

**Comment by Ornias1993** [comment]
I'll ask the guys at IX.

Because it's quite some work and it would be a shame if they don't think it will be in TrueNAS in 3 years.

**Comment by Ornias1993** [comment]
@asmod3us Got the answer, from an IX systems source. (I generally don't post names without permissions)

> Entire TrueNAS middleware is written in python3, so you can expect it to be available for all future versions of TrueNAS going forward

**Comment by thorsteneb** [comment]
> Might be less accessable for blueprint creators (not an issue if we only move the core code to python)

This can also be solved by being less prescriptive. Leave it up to the blueprint creator and look for an install.sh or install.py, ditto for update and build. Call those, the shebang in them will take care of bringing in the right interpreter.

**Comment by Ornias1993** [comment]
You are missing the point @thorsteneb what I wrote was just the fact less people may be able to contribute python. I already wrote we don't have to force blueprint contributors to do so, but I just documented it for future reference. 

I know you don't agree with some design choices we/I made, but this project is designed to have interoperatability and standardised formats. Thats the only reason we where able to do things like we did with Traefik and Grafana. 

But instead of complaining about it, maybe you should just explain what prescriptiveness you don't like... Because there isn't much prescriptiveness. With the new 1.3.0 code its even less prescriptive.

If you mean we have style guidelines: welcome to every self respective project.

**Comment by thorsteneb** [comment]
We have a misunderstanding. I am not complaining, I suggested that allowing either may be a good way forward. If that's already the plan: Grand!

**Comment by Ornias1993** [comment]
@thorsteneb To be clear: This is NOT a plan in any way, shape or form.
This is a brainstorm session.

For all I care this never will actually happen, but it is just here for documentation purposes.

**Comment by Ornias1993** [comment]
Okey, conclussion time:
- We clearly want to keep using bash for the blueprints themselves, to keep it accessable for everyone.
- We do want to port some or all functions of jailman itself (not the blueprints) to python

How can we do this in an organized way? 
I propose:
- We move to iocage plugins (example/placeholder repo's are already setup)
- We also move the jailman config to those repo's instead of `/blueprints` (in a /jailman folder for example)
- New jailman workflow would be: Install plugin -> download required jailman-scripts from plugin-repo -> execute those
- Plugin repo would be config files and bash only, no python
- Main repo could be pythonised as much as we would like

**Comment by Ornias1993** [comment]
Thanks for all the feedback, I formulated a proposal based on this and #196 
Hence closing.
