### ISSUE TITLE
Update error in jailman.sh

### ISSUE THREAD

**Issue by colemamd** [jailmanager/jailman#181]
# Issue Template

## Description

The jailman.sh script contains errors in the update section

### Detailed Bug Report
Line 199 references ```"${SCRIPT_DIR}"/jails/"${!blueprint}"/update.sh ``` folder and should be ```"${SCRIPT_DIR}"/blueprints/"${!blueprint}"/update.sh```

That line is also missing ```"${jail}"``` at the end.

### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1.  
2.  
3.

**Comment by Ornias1993** [comment]
FUCK. 
Thats a stupid mistake of mine. 

Thanks for mentioning, feel free to add it to your upcomming PR (as you have the files open and its quite arbitrary)
