### ISSUE TITLE
Error when installing traefik for the first time

### ISSUE THREAD

**Issue by thorsteneb** [jailmanager/jailman#182]
### Output
Firewall rules loaded.
Starting traefik.
environment: line 8: !traefik_service_port: unbound variable
ERR - status code 1
Command:  "${SCRIPT_DIR}"/blueprints/"${!blueprint}"/install.sh "${jail}"
Location:  ./jailman.sh, line 171
Status: 0
Stack trace:
    [1] main(): ./jailman.sh, line 171 -> main

### Steps to Reproduce

1.  Set config.yml with a basic traefikjail: config
2.  ./jailman.sh -i traefikjail

**Comment by Ornias1993** [comment]
Thanks for your report, will look into this after 1.2.3 merge! :)

**Comment by Ornias1993** [comment]
This specific error is fixed in dev now :)
