### ISSUE TITLE
Enhancement: Basic auth for traefik dashboard

### ISSUE THREAD

**Issue by thorsteneb** [jailmanager/jailman#184]
### Implementation steps

Desired user and password for dashboard would need to be present in config.yml, likely optional (but recommended) parameters.

The install.sh script for traefik would then:

Create /config/dynamic/auth_middlewares.toml 

```
[http.middlewares]
   [http.middlewares.auth.basicAuth]
     users = [
       "USERNAME:PASSWORDHASH"
    ]
```
 
To get the passwordhash to place into that file, print out the bcrypt hash of the password:
```
pkg install py37-pip
pip install bcrypt

python3.7 -c 'import bcrypt; print("\"USERNAME:", bcrypt.hashpw(b"PASSWORD", bcrypt.gensalt(rounds=10)).decode("ascii"),"\"",sep="")'
```

Example output for user admin, password password:
```"admin:$2b$10$NChczG41HP6xdZhvEMuujuzX0tpV.NGUllQsKezAwByQ.2rg.FU/q"```

For reference md5 hash, though this isn't considered secure:
```openssl passwd -apr1 PASSWORD```

Then in dashboard.toml add, right below entryPoints:
```middlewares = ["auth"]```

**Comment by Ornias1993** [comment]
I already added Basic Auth, please look into past PR's for more info.

**Comment by thorsteneb** [comment]
Please reconsider. This ask is specific to the traefik dashboard. I tried this by adding

traefik_auth_basic: username1:passwordhash1

to the traefikjail: configuration and taking care to $$ all $ in the passwordhash, so that bash remains happy with them. After jail creation, basic auth for the dashboard is nowhere to be found, no middleware entry, nothing in the dashboard.toml or traefik.toml.

I know I can add basic auth to the dashboard manually; I'm hoping that jailman will gain the ability to add it automatically.

**Comment by Ornias1993** [comment]
In that case: File a bug report.
WITHOUT you telling me how to do something thats already done.
