### ISSUE TITLE
Enhancement: Use latest repository for traefik jail

### ISSUE THREAD

**Issue by thorsteneb** [jailmanager/jailman#185]
Like it says in the subject. 

Rationale:
Creating a /usr/local/etc/pkg/repos/FreeBSD.conf that is set to "latest" for installation of traefik2 will support more DNS providers out of the box. dynu, for example, is supported from lego 3.5, which is part of traefik 2.2.

**Comment by Ornias1993** [comment]
i'll look into it, but I don't think it's wise.
We use a custom config generator and I can't guarantee it to stay up-to-date with the more frequent releases in lastest.

**Comment by Ornias1993** [comment]
@thorsteneb
I'm pretty happy with not using latest. We don't make releases often, I can't give any guarantee for installs using latest.

Yes I know they say the config synthax is the same... But I can't guarantee every little bit of our (quite complex) install-and-generate-config is going to work.

"Guarantee" is the thing here, I can't provide support for it nor can I release hotfixes fast enough to cover for any issues they may surface. When it comes to how vital Traefik is, I'm very hesitant in taking additional risks.

**Comment by Ornias1993** [comment]
That being said:
If we haver have more people working at this project and be able to push more releases, sure I'm all for it.
But as long as the people working on this don't even care enough to review releases(!), I can't affort to do this.

**Comment by Ornias1993** [comment]
@thorsteneb I want to propose a middleground:
Adding a general option to override the default train with latest, for every jail.

**Comment by Ornias1993** [comment]
I created #192 which would also cover this issue.
So i'll close this. Please reopen if you think #192 won't solve this for you!
