### ISSUE TITLE
Enhancement: Configure traefik to watch for configuration file changes

### ISSUE THREAD

**Issue by thorsteneb** [jailmanager/jailman#186]
In order to easily add routers or make changes to routers without needing to reload the traefik service, add ```watch = true``` to traefik.toml:

```
[providers]
  [providers.file]
    directory = "/config/dynamic"
    watch = true
```   

I realize it is possible this was left out on purpose.

**Comment by Ornias1993** [comment]
changes are already watched afaik.

**Comment by thorsteneb** [comment]
Yup, confirmed. Looks like watch = true is the default. Thanks!

**Comment by Ornias1993** [comment]
NP :)
