### ISSUE TITLE
Basic auth for traefik dashboard

### ISSUE THREAD

**Issue by thorsteneb** [jailmanager/jailman#187]
### Detailed Bug Report

Add to config.yml in traefikjail: section

traefik_auth_basic: username1:passwordhash1

while taking care to $$ all $ in the passwordhash, so that bash remains happy with them. After jail creation, basic auth for the dashboard is nowhere to be found, no middleware entry, nothing in the dashboard.toml or traefik.toml.

### Steps to Reproduce

1. Configure basic auth for traefikjail in config.yml  
2.  ./jailman.sh -i traefikjail

**Comment by Ornias1993** [comment]
traefikdashboard indeed doesn't seem to be compatible with basicauth yet. This really needs to be added.
Small sidenote: You don't need to add $$ to every $, all escaping is already done automatically...
Me and @asmod3us spend quite some time going over it.

**Comment by Ornias1993** [comment]
Just so we know, you did try this with #169 and not with dev right?
Because dev doesn't include this yet...

**Comment by thorsteneb** [comment]
It would have been dev. I legit don't know which branch that PR is in.

**Comment by Ornias1993** [comment]
Ahh, look that explains a lot of your issues....
Traefik is not supposed to fully work on dev yet, it was a two-part or three-part PR...

Part 1 (which is basically just adding a traefik jail) has been merged into dev and part 2 (#169) include compatibility fixes...

That being said: Traefik needs A LOT of work still, I hope to have it working as promised on dev before 01-08-2020

**Comment by Ornias1993** [comment]
Moved to the 1.3.0 PR description

**Comment by Ornias1993** [comment]
I expect to have this and traefik done (including documentation), before the 31st.
All features should be in for traefik now, so it's mostly just making sure everything works correctly (while this clearly is not working correctly) and writing it down.
