### ISSUE TITLE
Enhancement: Traefik statistics via influxdb and grafana

### ISSUE THREAD

**Issue by thorsteneb** [jailmanager/jailman#188]
I am thinking of tinkering with integrating the influxdb and grafana jails with traefik, and add a link_influxdb option to the traefik jail. Dashboard something like https://grafana.com/grafana/dashboards/10902 with the influxdb toml config (adapted to traefik2) from https://grafana.com/grafana/dashboards/10479

Before I go haring off in that direction: Does this fit with your vision? Or are you preferring to get traefik metrics via prometheus?

**Comment by Ornias1993** [comment]
This does fit my vision and is actually already planned. Afaik I even referenced it a few times.
But there is not final version of traefik merged yet, so I find it distracting to allow feature/enhancement request for non-existing features (unless it's an enhancement to slightly mod already existing beta code, but in those cases I rather recieve PR's or PR comments)

**Comment by Ornias1993** [comment]
@thorsteneb Just so you know: It just got merged into dev
