### ISSUE TITLE
Discussion: jail and VM resource monitoring via grafana

### ISSUE THREAD

**Issue by thorsteneb** [jailmanager/jailman#189]
This is a little aspirational. Jailman could bring in jail and VM metrics via prometheus/grafana, along the lines of https://www.bsdstore.ru/en/articles/cbsd_with_grafana.html, just that nginx would be traefik, and the whole thing would fit into the blueprint framework of jailman.

Desirable, as far as you are concerned?

If so, shove prometheus into the grafana jail as CBSD does, or keep that separate? I have no experience with prometheus / grafana currently and don't know whether having them in separate jails or in one jail is recommended best practice.

**Comment by Ornias1993** [comment]
Prometheus is currently planned to be included.
People are, as always, but it isn't an issue thats worth documenting.

Some extra metrics for traefik are already planned to be included. But currently there isn't even a final traefik version to review, so please hold your horses.
