### ISSUE TITLE
Traefik cert_wildcard_domain may cause issues with certain DNS providers, here: dynu

### ISSUE THREAD

**Issue by thorsteneb** [jailmanager/jailman#190]
### Traefik's cert_wildcard_domain as implemented causes Let's Encrypt cert issue to fail with dynu.com

Currently, dashboard.toml contains, after install and with cert_wildcard_domain configured:

```
          [[http.routers.traefik.tls.domains]]
            main = "example.com"
            sans = ["*.example.com"]
```

This is correct as per traefik documentation. It also causes dynu to fail to process DNS01 validation, and Let's Encrypt staging cannot issue a cert.

Changing it thusly will resolve this issue and certs can be issued:

```
          [[http.routers.traefik.tls.domains]]
            main = "*.example.com"
            sans = ["example.com"]
```

This, also, is correct as per traefik documentation.

### Steps to Reproduce

1.  Set cert_wildcard_domain in config.yml
2.  Set dns_provider to one that has this issue, e.g. dynu
3.  ./jailman.sh -i
4. Observe cert issuing failures in /config/traefik.log

**Comment by Ornias1993** [comment]
Formally the wildcard should be the alternative name, this is an upstream bug basically.
