### ISSUE TITLE
Foundry VTT

### ISSUE THREAD

**Issue by thorsteneb** [jailmanager/jailman#51]
I am setting up a Foundry VTT jail (node.js app), with an nginx and coturn jail alongside. First pass will be manual. After that, a script would be great, and you have a great framework here.

Would you accept a PR for Foundry VTT, nginx and coturn? May take a while to create, manual first.

**Comment by Ornias1993** [comment]
In general: nice idea.

However:
What is your goal with NGINX? reverse proxy?
We have an open issue for a general reverse-proxy jail.

I think it would be prefered (design wise) to seperate at least the Foundry VTT and coturn jails (considering coturn might also be used by other jails in the future)

**Comment by Ornias1993** [comment]
As Foundry VTT is not a much requested app, and the choice for traefik as reverse proxy is final, i'm going to close it.

Don't be discouraged @thorsteneb you are still free to send the PR and big chance it would get merged. I just don't think this is an "issue" that is going to every be resolved by anyone but yourself....
