### ISSUE TITLE
Add Bazarr (subtitle-grabber)

### ISSUE THREAD

**Issue by coconutoil** [jailmanager/jailman#64]
It's basically a background subtitle-grabber for anything that sonarr and radarr have indexed.

https://github.com/morpheus65535/bazarr

:)

**Comment by Ornias1993** [comment]
Didn't know that one, Thanks for the reminder.
Yes this is a worthwhile addition :)

**Comment by Ornias1993** [comment]
Considering it seems to be likely we are going to add Jellyfin somewhere Q3/Q4 this year and jellyfin's subtitle processing is not on par with plex according to some, i'm going to push this to a v1.2.x minor release.

**Comment by Ornias1993** [comment]
@coconutoil A basic version of a bazarr blueprint has just been merged into the dev branch. It should be available when 1.3.0 launches :)
